### ISSUE TITLE
Discussion: Integrate the payout function into the severities 

### ISSUE THREAD

**Issue by shayzluf** [hats-finance/hats-contracts#95] opened 2022-02-23 07:51 UTC
In order to have a better user experiance from the hacker side of things I would like to consider adding the payout function to the smart contract
https://docs.google.com/document/d/157koANfmBxzsyX3MQvDioGo8xfQHfiH0uZorEGNP10Q/edit?usp=sharing

**Comment by jellegerbrandy** [comment] 2022-04-11 10:42
closing this as it is a duplicate of #104

**Closed by jellegerbrandy** 2022-04-11 10:42 UTC
